import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/server/nav";
import Animations from "@/components/client/Animations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="px-16 pt-32 pb-16 flex justify-center">
              <div className="w-full max-w-280 space-y-8 md:grid md:grid-cols-2 md:space-y-0 text-white">
                  <Nav />
                  <div id="page-content">
                      {children}
                  </div>
              </div>
          </div>
          <Animations />
      </body>
    </html>
  );
}
